import dataAnalyis from './bussiness.png';
import electrical from './electrical.jpg';
import oil from './oil.jpg';
import website  from './website.jpg';
import finacial from './electrical.jpg';
import banner from './banner.jpg';
import food  from './foodsupply.jpg';
import cctv from './cctv.jpg';
import repair from './electrical.jpg';
import computer from './finacial.jpg';
import anitha from './anitha alex.jpg';
import peter from './Peter serikali.jpg';
import leticia from './leticia.jpg';
import stephe from './stephen.jpg';
import badevits from './badehe.mp4';
import ally from './ally juma.jpg';
import questions  from './80125-art-character-question-fictional-mark-animation-cartoon.png';
import technology from './7-2-technology-picture.png';
import  logo from './logo_size-removebg-preview.png';
export  {dataAnalyis,logo, food, cctv,electrical,oil,website,finacial,banner,repair,computer,leticia,peter,anitha,stephe,badevits,ally,questions,technology}; 